# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NetworkMapper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NetworkMapper
  pod 'MMLanScan'
  

  target 'NetworkMapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NetworkMapper-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NetworkMapper-tvOS

  target 'NetworkMapper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
